# Conda environment, that includes all packages that are necessary for
# the complete Biotite development process.

name: springcraft-dev

channels:
  - conda-forge

dependencies:
  - numpy >=1.15,<1.25
  - biotite >=0.32<0.40
  - prody >=2.1
  - pytest >=5.2
  - matplotlib >=3.3
  - poetry >=1.0
  - jinja2 <3.1
  - scipy <=1.13.1
  - sphinx >=3.0
  - sphinx-gallery =0.9.0
  - numpydoc >=0.8
  - ammolite >=0.8
  - rpy2
  - r-bio3d
